"use client";
import {useEffect,useMemo,useState} from "react";
import {ModelLoader} from "@/components/model/model-loader";
import {ModelSelector} from "@/components/model/model-selector";
import {getDeviceCapabilities} from "@/lib/device/capabilities";
import {loadKiteModel,streamKiteResponse} from "@/lib/webllm/engine";
import {DEFAULT_MODEL_ID,getKiteModel,KITE_MODELS} from "@/lib/webllm/models";
import {getSelectedModelId,setSelectedModelId} from "@/lib/storage/settings-storage";
import type {ChatMessage} from "@/types/chat";
const SYSTEM_PROMPT="Você é o Kite, um assistente local executado no navegador. Seja útil, direto e transparente sobre suas limitações.";
const makeId=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;
export function KiteShell(){
 const [selectedModelId,setSelectedModelIdState]=useState(DEFAULT_MODEL_ID),[webgpuReady,setWebgpuReady]=useState<boolean|null>(null),[progress,setProgress]=useState(0),[status,setStatus]=useState("Aguardando modelo…"),[loading,setLoading]=useState(false),[ready,setReady]=useState(false),[input,setInput]=useState(""),[sending,setSending]=useState(false),[messages,setMessages]=useState<ChatMessage[]>([]);
 const selectedModel=useMemo(()=>getKiteModel(selectedModelId)??KITE_MODELS[0],[selectedModelId]);
 useEffect(()=>{setSelectedModelIdState(getSelectedModelId(DEFAULT_MODEL_ID));void getDeviceCapabilities().then(c=>setWebgpuReady(c.webgpu==="supported"));},[]);
 async function load(){if(loading||webgpuReady!==true)return;setLoading(true);setStatus("Inicializando WebLLM…");try{await loadKiteModel(selectedModel.id,r=>{setProgress(Math.round(r.progress*100));setStatus(r.text);});setProgress(100);setStatus("Modelo pronto");setReady(true);}catch(e){console.error(e);setStatus("Não foi possível inicializar o modelo.");}finally{setLoading(false);}}
 async function send(){const content=input.trim();if(!content||!ready||sending)return;setInput("");setSending(true);const user={id:makeId(),role:"user" as const,content,createdAt:Date.now()},assistant={id:makeId(),role:"assistant" as const,content:"",createdAt:Date.now()},next=[...messages,user];setMessages([...next,assistant]);try{await streamKiteResponse([{id:"system",role:"system",content:SYSTEM_PROMPT,createdAt:0},...next],token=>setMessages(cur=>cur.map(m=>m.id===assistant.id?{...m,content:m.content+token}:m)));}catch(e){console.error(e);setMessages(cur=>cur.map(m=>m.id===assistant.id?{...m,content:"Erro ao gerar a resposta. Verifique WebGPU e o modelo."}:m));}finally{setSending(false);}}
 if(!ready)return <main className="page-shell"><div className="brand-mark">K</div><ModelSelector models={KITE_MODELS} selectedId={selectedModel.id} disabled={loading} onChange={v=>{setSelectedModelIdState(v);setSelectedModelId(v);}}/><ModelLoader model={selectedModel} progress={progress} status={status} webgpuReady={webgpuReady} loading={loading} ready={ready} onLoad={load}/>{webgpuReady===false&&<p className="error-note">Este navegador ou dispositivo não disponibilizou WebGPU para o Kite.</p>}</main>;
 return <main className="chat-shell"><header className="chat-header"><div><div className="brand-row"><span className="brand-dot"/><strong>Kite</strong></div><span className="model-caption">{selectedModel.name} · local</span></div><span className="local-badge">WebGPU</span></header><section className="messages" aria-live="polite">{messages.length===0?<div className="empty-state"><div className="brand-mark small">K</div><h1>Como posso ajudar?</h1><p>O Kite está conectado ao WebLLM e pronto para inferência local.</p></div>:messages.map(m=><article key={m.id} className={`message ${m.role}`}><span className="message-role">{m.role==="user"?"Você":"Kite"}</span><p>{m.content}</p></article>)}</section><form className="composer" onSubmit={e=>{e.preventDefault();void send();}}><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Fale com o Kite…" rows={3} disabled={sending}/><div className="composer-footer"><span>{sending?"Gerando localmente…":"Seu texto não precisa sair do dispositivo."}</span><button className="primary-button" disabled={!input.trim()||sending}>Enviar</button></div></form></main>;
}
